version: '3.1'

services:
  postgres:
    image: 'postgres:14'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data